version: '3.2'
services:
  mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ReallyStrongPwd1234%^&*
      MSSQL_DB: test_ci
      MSSQL_PID: Developer
    networks:
      - dbnet
    ports:
      - "1433:1433"

networks:
  dbnet:
    driver: bridge
